name: Replit Auto Wake

on:
  schedule:
    - cron: '*/5 * * * *'  # Alle 5 Minuten
  workflow_dispatch:

jobs:
  ping_bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Bridge-URL aufrufen (Vercel Ping)
        run: |
          curl -s --max-time 10 --retry 2 --retry-delay 5 --fail \
          https://wake-bot.vercel.app/api/ping || \
          echo "⚠️ Bridge-Ping fehlgeschlagen – Bot evtl. offline"

      - name: "Optional: Status loggen"
        run: |
          echo "📡 Ping wurde gesendet: $(date)"

