name: Replit Auto Wake

on:
  schedule:
    - cron: '*/5 * * * *'  # Alle 5 Minuten
  workflow_dispatch:

jobs:
  ping_replit:
    runs-on: ubuntu-latest
    steps:
      - name: URL aufrufen
        run: |
          curl -s --max-time 10 --retry 2 --retry-delay 5 --fail \
          https://317797e1-89aa-42d2-a9b6-c25cd8a0c982-00-3s387r4cb4eli.riker.replit.dev:8080/ || \
          echo "Bot scheint offline zu sein - Wakeup-Versuch schlägt fehl."

      - name: "Optional: Status loggen"
        run: |
          echo "Ping wurde gesendet: $(date)"
